### ISSUE TITLE
[INIT] 초기 폴더 구조 생성

### ISSUE THREAD

**Issue by sootudio** [Team-Daengnyang/moneynyang-server#1]
### 작업 개요
- 초기 폴더 구조 생성

### 작업 내용
- 프로젝트 내에 정해진 API 명세서를 따라 초기 폴더 구조를 생성
- 각 도메인은 controller, repository, service/dto, entity 패키지로 나눠지도록 생성

### Todo list
- [x] fans 도메인 구조 생성
- [x] cashwalks 도메인 구조 생성
- [x] bankbooks 도메인 구조 생성
- [x] members 도메인 구조 생성
- [x] pets 도메인 구조 생성
- [x] insurances 도메인 구조 생성
- [x] deposits 도메인 구조 생성

**Comment by a-young-kim** [comment]
P5 : 확인했습니다. 수고하셨어요
