### ISSUE TITLE
[FEAT] 펫 정보를 이용한 데이터 분석

### ISSUE THREAD

**Issue by a-young-kim** [Team-Daengnyang/moneynyang-server#121]
### 작업 개요
- 반려동물 성별, 반려동물 타입을 이용한 분석
- 반려동물 품종과 생년월일이 null이 아닐 경우 해당 데이터를 이용하여 분석

### 작업 내용
- 입출금 계좌에 대한 페이지

- [ ] 반려동물 성별 + 타입을 이용한 분석 
   - 반려동물들에 대한 합 목표 금액 비교
- [ ] 반려동물 품종을 이용한 분석
  - 반려동물들에 대한 평균 목표 금액
- [ ] 반려동물 품종을 이용한 분석
  - 반려동물들에 대한 평균 목표 금액
- [ ] 반려동물에 대한 결제 횟수

### Todo list
-

**Comment by csb9427** [comment]
다른 API를 사용하면 됩니다 닫도록 하겠습니다.
