### ISSUE TITLE
[FEAT] 소비 데이터 분석 API 구현

### ISSUE THREAD

**Issue by a-young-kim** [Team-Daengnyang/moneynyang-server#127]
### 작업 개요
- 입출금 계좌를 이용한 데이터 분석

### 작업 내용
- [ ] 입출금 계좌를 이용한 데이터 분석
  - 반려, 식비, 쇼핑, 교통, 기타로 데이터 분석

### Todo list
- [ ] 출금하기 기능에 메모 남기기 
   -> 랜덤
- [x] 조회 시 데이터를 불러와서 시각화
- [x] DB에 erd 수정
