### ISSUE TITLE
[FIX] 반려 동물 성별 컬럼명 변경

### ISSUE THREAD

**Issue by a-young-kim** [Team-Daengnyang/moneynyang-server#44]
### 예외 개요
-  반려 동물 성별 컬럼명 변경

### 예외 원인
- 

### 작업 내용
- 반려동물 성별 컬럼명을 petSex에서 petGender로 변경

### Todo list
- [ ] response dto 수정
- [ ] entity 수정
- [ ] request dto 수정
- [ ] api 명세서 수정
- [ ] db 수정
