### ISSUE TITLE
[FEAT] 캐시워크 일지 등록

### ISSUE THREAD

**Issue by sootudio** [Team-Daengnyang/moneynyang-server#90]
### 작업 개요
- 캐시워크 일지 등록 API 개발

### 작업 내용
- 입력값은 content랑 날짜

### Todo list
- [ ] request, response dto 생성
- [ ] repository 생성
- [ ] controller의 일지 등록 메소드 구현
- [ ] service의 일지 등록 메소드 구현
