### ISSUE TITLE
[FEAT] 이달 중 일지 쓴 날들 조회하기

### ISSUE THREAD

**Issue by sootudio** [Team-Daengnyang/moneynyang-server#96]
### 작업 개요
- 이달 중 일지 쓴 날들 조회하기

### 작업 내용
- 달력에 점만 찍히면 되므로 id와 날짜만 return

### Todo list
- [ ] response dto 생성
- [ ] Controller 메소드 추가
- [ ] Service 메소드 추가
